=== aulenbac/FWS-ESA-WorkPlanSpecies/documentation/workplan_species-schema.json
{
  "definitions": {
    "items": {
      "$id": "#/items",
      "type": [
        "object",
        "array"
      ],
      "title": "Generic container for items in a dataset",
      "description": "A JSON array or object property containing one or more items in a dataset or data structure within a dataset."
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://data.usgs.gov/property_registry/",
  "type": [
    "array",
    "object"
  ],
  "title": "FWS National Listing Workplan Species",
  "description": "A processed dataset of the FWS National Listing Workplan species from original source material. Includes the addition of properties to aid in name/identifier lookup from other sources.",
  "items": {
    "$ref": "#/definitions/items",
    "required": [
      "Guild",
      "Species Name (Common)",
      "Scientific Name",
      "Lead FWS Regional Office",
      "Proposed FWS Decision Timeframe (Fiscal Year)",
      "Range",
      "Bin",
      "ECOS Link",
      "ITIS TSN",
      "Lookup Name"
    ]
  },
    "properties": {
      "Guild": {
        "$id": "#/items/properties/Guild",
        "type": "string",
        "title": "Species Guild",
        "description": "A high level grouping of species into guilds. This property was added by USGS Ecosystems Mission Area staff to help organize the original FWS list.",
        "enum": [
          "Amphibians",
          "Birds",
          "Flowering Plants",
          "Insects",
          "Mammals",
          "Snails",
          "Bivalves",
          "Crustaceans",
          "Fishes",
          "Non-Flowering Plants",
          "Reptiles"
        ]
      },
      "Species Name (Common)": {
        "$id": "#/items/properties/Species Name (Common)",
        "type": "string",
        "title": "Species Common Name",
        "description": "A common (vernacular) name for the species.",
        "examples": [
          "Arizona toad"
        ]
      },
      "Scientific Name": {
        "$id": "#/items/properties/Scientific Name",
        "type": "string",
        "title": "Scientific Name",
        "description": "The scientific (latin) name for the species.",
        "examples": [
          "Bufo microscaphus microscaphus"
        ]
      },
      "Lead FWS Regional Office": {
        "$id": "#/items/properties/Lead FWS Regional Office",
        "type": "string",
        "title": "Lead FWS Regional Office",
        "description": "The FWS Regional Office with lead for the listing process.",
        "enum": [
          "Region 1 - Pacific (Northwest)",
          "Region 2 - Southwest",
          "Region 3 - Midwest",
          "Region 4 - Southeast",
          "Region 5 - Northeast",
          "Region 6 - Mountain-Prairie",
          "Region 7 - Alaska",
          "Region 8 - Pacific Southwest"
        ]
      },
      "Proposed FWS Decision Timeframe (Fiscal Year)": {
        "$id": "#/items/properties/Proposed FWS Decision Timeframe (Fiscal Year)",
        "type": "integer",
        "title": "Proposed fws decision timeframe (fiscal year)",
        "description": "The proposed time frame in which the FWS will seek to make a decision on listing.",
        "enum": [
          2023,
          2022,
          2021,
          2020,
          2017,
          2019,
          2018
        ]
      },
      "Range": {
        "$id": "#/items/properties/Range",
        "type": "string",
        "title": "Geographic Range",
        "description": "A list of US states and other areas considered to be in the range of the species.",
        "examples": [
          "AZ, CA, NM, NV, UT"
        ]
      },
      "Bin": {
        "$id": "#/items/properties/Bin",
        "type": [
          "null",
          "string"
        ],
        "title": "Bin",
        "description": "A text value for a listing workplan bin assignment.",
        "enum": [
          null,
          "LPN 9",
          "LPN 2",
          "LPN 8",
          "LPN 6",
          "LPN 5",
          "LPN 3"
        ]
      },
      "ECOS Link": {
        "$id": "#/items/properties/ECOS Link",
        "type": [
          "null",
          "string"
        ],
        "title": "ECOS Link",
        "description": "Web link to a species information page in the USFWS Ecological Conservation Online System. It is not clear when or by whom this property was added to original source material.",
        "examples": [
          "https://ecos.fws.gov/ecp/species/2077"
        ]
      },
      "ITIS TSN": {
        "$id": "#/items/properties/ITIS TSN",
        "type": [
          "string",
          "null"
        ],
        "title": "ITIS TSN",
        "description": "The ITIS Taxonomic Serial Number added into the data from processing steps.",
        "examples": [
          "207135"
        ]
      },
      "Lookup Name": {
        "$id": "#/items/properties/Lookup Name",
        "type": "string",
        "title": "Lookup Name",
        "description": "The most appropriate name to use in species lookup based on processing steps. In some cases, an original name string contained species identification information that would hinder rather than help in API searches, and these were cut down to the best name string available.",
        "examples": [
          "Bufo microscaphus microscaphus"
        ]
      },
      "Valid ITIS Scientific Name": {
        "$id": "#/items/properties/Valid ITIS Scientific Name",
        "type": "string",
        "title": "Valid ITIS scientific Name",
        "description": "Based on previous processing steps, when applicable the valid scientific name according to ITIS was added to serve as an additional name in searches.",
        "examples": [
          "Anaxyrus microscaphus"
        ]
      },
      "Valid ITIS TSN": {
        "$id": "#/items/properties/Valid ITIS TSN",
        "type": "string",
        "title": "Valid ITIS TSN",
        "description": "Based on previous processing steps, when applicable the valid TSN  according to ITIS was added.",
        "examples": [
          "773525"
        ]
      }
    }
  }

=== aulenbac/FWS-ESA-WorkPlanSpecies/cache/workplan_species.json
[{"Guild": "Amphibians", "Species Name (Common)": "Cascade torrent salamander", "Scientific Name": "Rhyacotriton cascadae", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2023, "Range": "OR, WA", "Bin": null, "Lookup Name": "Rhyacotriton cascadae", "ECOS Link": "https://ecos.fws.gov/ecp/species/1375", "ITIS TSN": "550250"}, {"Guild": "Amphibians", "Species Name (Common)": "Cascades frog", "Scientific Name": "Rana cascadae", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2022, "Range": "OR, WA", "Bin": null, "Lookup Name": "Rana cascadae", "ECOS Link": "https://ecos.fws.gov/ecp/species/7827", "ITIS TSN": "173450"}, {"Guild": "Amphibians", "Species Name (Common)": "Columbia torrent salamander", "Scientific Name": "Rhyacotriton kezeri", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2021, "Range": "OR, WA", "Bin": null, "Lookup Name": "Rhyacotriton kezeri", "ECOS Link": "https://ecos.fws.gov/ecp/species/3376", "ITIS TSN": "550251"}, {"Guild": "Amphibians", "Species Name (Common)": "Oregon slender salamander", "Scientific Name": "Batrachoseps wrighti", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2020, "Range": "OR, WA", "Bin": null, "Lookup Name": "Batrachoseps wrighti", "ECOS Link": "https://ecos.fws.gov/ecp/species/913", "ITIS TSN": "173712"}, {"Guild": "Birds", "Species Name (Common)": "Mt. Rainier white-tailed ptarmigan", "Scientific Name": "Lagopus leucura rainierensis", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2020, "Range": "WA", "Bin": null, "Lookup Name": "Lagopus leucura rainierensis", "ECOS Link": "https://ecos.fws.gov/ecp/species/9234", "ITIS TSN": "677706"}, {"Guild": "Birds", "Species Name (Common)": "northern spotted owl", "Scientific Name": "Strix occidentalis caurina", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2017, "Range": "CA, OR, WA", "Bin": null, "Lookup Name": "Strix occidentalis caurina", "ECOS Link": "https://ecos.fws.gov/ecp/species/1123", "ITIS TSN": "177926"}, {"Guild": "Birds", "Species Name (Common)": "Tinian monarch", "Scientific Name": "Monarcha takatsukasae", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2017, "Range": "MP", "Bin": null, "Lookup Name": "Monarcha takatsukasae", "ECOS Link": "https://ecos.fws.gov/ecp/species/6613", "ITIS TSN": "178684"}, {"Guild": "Birds", "Species Name (Common)": "tufted puffin", "Scientific Name": "Fratercula cirrhata", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2019, "Range": "CA, OR, WA", "Bin": null, "Lookup Name": "Fratercula cirrhata", "ECOS Link": "https://ecos.fws.gov/ecp/species/430", "ITIS TSN": "177032"}, {"Guild": "Flowering Plants", "Species Name (Common)": "mountain blue-eyed grass", "Scientific Name": "Sisyrinchium sarmentosum", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2018, "Range": "WA", "Bin": null, "Lookup Name": "Sisyrinchium sarmentosum", "ECOS Link": "https://ecos.fws.gov/ecp/species/5588", "ITIS TSN": "43273"}, {"Guild": "Flowering Plants", "Species Name (Common)": "sand dune (or silvery) phacelia", "Scientific Name": "Phacelia argentea", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2021, "Range": "OR", "Bin": null, "Lookup Name": "Phacelia argentea", "ECOS Link": "https://ecos.fws.gov/ecp/species/599", "ITIS TSN": "31454"}, {"Guild": "Insects", "Species Name (Common)": "Franklin's bumblebee", "Scientific Name": "Bombus franklini", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2018, "Range": "OR", "Bin": null, "Lookup Name": "Bombus franklini", "ECOS Link": "https://ecos.fws.gov/ecp/species/7022", "ITIS TSN": "714804"}, {"Guild": "Insects", "Species Name (Common)": "Island marble butterfly", "Scientific Name": "Euchloe ausonides insulanus", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2017, "Range": "WA", "Bin": "LPN 3", "Lookup Name": "Euchloe ausonides insulanus", "ECOS Link": null, "ITIS TSN": null}, {"Guild": "Insects", "Species Name (Common)": "sand verbena moth", "Scientific Name": "Copablepharon fuscum", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2019, "Range": "WA", "Bin": null, "Lookup Name": "Copablepharon fuscum", "ECOS Link": "https://ecos.fws.gov/ecp/species/9053", "ITIS TSN": null}, {"Guild": "Mammals", "Species Name (Common)": "red tree vole", "Scientific Name": "Arborimus longicaudus", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2019, "Range": "OR", "Bin": "LPN 9", "Lookup Name": "Arborimus longicaudus", "ECOS Link": "https://ecos.fws.gov/ecp0/profile/speciesProfile?spcode=A0J3", "ITIS TSN": "180353"}, {"Guild": "Snails", "Species Name (Common)": "Burrington (keeled) jumping-slug", "Scientific Name": "Hemphillia burringtoni", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2021, "Range": "OR, WA", "Bin": null, "Lookup Name": "Hemphillia burringtoni", "ECOS Link": "https://ecos.fws.gov/ecp/species/8641", "ITIS TSN": "77089"}, {"Guild": "Snails", "Species Name (Common)": "Chelan mountain snail", "Scientific Name": "Oreohelix n. sp. 1", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2023, "Range": "WA", "Bin": null, "Lookup Name": "Oreohelix", "ECOS Link": null, "ITIS TSN": null}, {"Guild": "Snails", "Species Name (Common)": "Columbia Oregonian snail", "Scientific Name": "Cryptomastix hendersoni", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2022, "Range": "OR, WA", "Bin": null, "Lookup Name": "Cryptomastix hendersoni", "ECOS Link": "https://ecos.fws.gov/ecp/species/8598", "ITIS TSN": "77509"}, {"Guild": "Snails", "Species Name (Common)": "Dalles sideband snail", "Scientific Name": "Monadenia fidelis minor", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2021, "Range": "OR, WA", "Bin": null, "Lookup Name": "Monadenia fidelis minor", "ECOS Link": "https://ecos.fws.gov/ecp/species/4369", "ITIS TSN": null}, {"Guild": "Snails", "Species Name (Common)": "evening fieldslug", "Scientific Name": "Deroceras hesperium", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2022, "Range": "OR, WA", "Bin": null, "Lookup Name": "Deroceras hesperium", "ECOS Link": "https://ecos.fws.gov/ecp/species/8642", "ITIS TSN": "77303"}, {"Guild": "Snails", "Species Name (Common)": "Hoko vertigo", "Scientific Name": "Vertigo sp.", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2023, "Range": "WA", "Bin": null, "Lookup Name": "Vertigo", "ECOS Link": null, "ITIS TSN": null}, {"Guild": "Snails", "Species Name (Common)": "Puget Oregonian snail", "Scientific Name": "Cryptomastix devia", "Lead FWS Regional Office": "Region 1 - Pacific (Northwest)", "Proposed FWS Decision Timeframe (Fiscal Year)": 2020, "Range": "OR, WA", "Bin": null, "Lookup Name": "Cryptomastix devia", "ECOS Link": "https://ecos.fws.gov/ecp/species/294", "ITIS TSN": "77506"}, {"Guild": "Amphibians", "Species Name (Common)": "Arizona toad", "Scientific Name": "Bufo microscaphus microscaphus", "Lead FWS Regional Office": "Region 2 - Southwest", "Proposed FWS Decision Timeframe (Fiscal Year)": 2022, "Range": "AZ, CA, NM, NV, UT", "Bin": null, "Lookup Name": "Bufo microscaphus microscaphus", "ECOS Link": "https://ecos.fws.gov/ecp/species/2077", "ITIS TSN": "207135", "Valid ITIS Scientific Name": "Anaxyrus microscaphus", "Valid ITIS TSN": "773525"}, {"Guild": "Amphibians", "Species Name (Common)": "Blanco blind salamander", "Scientific Name": "Eurycea robusta", "Lead FWS Regional Office": "Region 2 - Southwest", "Proposed FWS Decision Timeframe (Fiscal Year)": 2021, "Range": "TX", "Bin": null, "Lookup Name": "Eurycea robusta", "ECOS Link": "https://ecos.fws.gov/ecp/species/29", "ITIS TSN": "586344"}, {"Guild": "Amphibians", "Species Name (Common)": "Cascade Caverns salamander", "Scientific Name": "Eurycea latitans", "Lead FWS Regional Office": "Region 2 - Southwest", "Proposed FWS Decision Timeframe (Fiscal Year)": 2021, "Range": "TX", "Bin": null, "Lookup Name": "Eurycea latitans", "ECOS Link": "https://ecos.fws.gov/ecp/species/4624", "ITIS TSN": "208320"}, {"Guild": "Amphibians", "Species Name (Common)": "Comal blind salamander", "Scientific Name": "Eurycea tridentifera", "Lead FWS Regional Office": "Region 2 - Southwest", "Proposed FWS Decision Timeframe (Fiscal Year)": 2021, "Range": "TX", "Bin": null, "Lookup Name": "Eurycea tridentifera", "ECOS Link": "https://ecos.fws.gov/ecp/species/2890", "ITIS TSN": "173696"}, {"Guild": "Amphibians", "Species Name (Common)": "Comal Springs salamander", "Scientific Name": "Eurycea sp.", "Lead FWS Regional Office": "Region 2 - Southwest", "Proposed FWS Decision Timeframe (Fiscal Year)": 2021, "Range": "TX", "Bin": null, "Lookup Name": "Eurycea", "ECOS Link": null, "ITIS TSN": null}, {"Guild": "Amphibians", "Species Name (Common)": "Texas salamander", "Scientific Name": "Eurycea nana", "Lead FWS Regional Office": "Region 2 - Southwest", "Proposed FWS Decision Timeframe (Fiscal Year)": 2021, "Range": "TX", "Bin": null, "Lookup Name": "Eurycea nana", "ECOS L
